project:
  type: website

website:
  title: "ISSS608-VAA_demo"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: HO_EX01.qmd
          - text: "Hands-on Exercise 2"
            href: HO_EX02.qmd
          - text: "Hands-on Exercise 3.1"
            href: HO_EX03_1.qmd
          - text: "Hands-on Exercise 3.2"
            href: HO_EX03_2.qmd
          - text: "About"
            href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "On this page"
    toc-location: right
    toc-depth: 3