project:
  type: website
  output-dir: _site

website:
  title: "ISSS608"
  navbar:
    background: "#d8f3f0" 
    foreground: "#006d6f"
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: HO_EX01.qmd
          - text: "Hands-on Exercise 2"
            href: HO_EX02.qmd
          - text: "Hands-on Exercise 3.1"
            href: HO_EX03_1.qmd
          - text: "Hands-on Exercise 3.2"
            href: HO_EX03_2.qmd
          - text: "Hands-on Exercise 4.1"
            href: HO_EX04_01.qmd
          - text: "Hands-on Exercise 4.2"
            href: HO_EX04_02.qmd
          - text: "Hands-on Exercise 4.3"
            href: HO_EX04_03.qmd
          - text: "Hands-on Exercise 4.4"
            href: HO_EX04_04.qmd
          - text: "Hands-on Exercise 5.1"
            href: HO_EX05_1.qmd
          - text: "Hands-on Exercise 5.2"
            href: HO_EX05_2.qmd
          - text: "Hands-on Exercise 5.3"
            href: HO_EX05_3.qmd
          - text: "Hands-on Exercise 5.4"
            href: HO_EX05_4.qmd
          - text: "Hands-on Exercise 5.5"
            href: HO_EX05_5.qmd
      - text: "Take-home Exercise"
        menu:
          - text: "Take-home Exercise 1"
            href: TH_EX01.qmd
          - text: "Motor Insurance Portfolio Insights"
            href: Executive_Summary_revealjs.qmd
      - text: "About"
        href: about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: "On this page"
    toc-location: right
    toc-depth: 3