project:
  type: website

website:
  title: "ISSS608-VAA_demo"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: HO_EX01.qmd
          - text: "About"
            href: about.qmd

format:
  html:
    theme: cosmo
    css: styles.css